{{- if and (or .Values.etrip.use_redis .Values.etripng.enabled) (eq .Values.etrip.redis_flavour "vanilla") -}}
{{/* The config file, if required */}}
{{- if .Values.redis.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-redis-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
data:
  redis.conf: |-
    {{- range $key, $value := .Values.redis.config }}
    {{ $key }} {{ $value }}
    {{- end }}
---
{{- end }}
{{/* The deployment */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      {{- with .Values.affinity.redis }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: redis
        command:
        - /bin/sh
        - -c
        - redis-server {{ if .Values.redis.config }}/etc/redis/redis.conf{{ end }} --bind 0.0.0.0 --requirepass $REDISCLI_AUTH
        image: {{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }}
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        env:
        - name: REDISCLI_AUTH
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: session
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        resources:
          {{- toYaml .Values.resources.redis | nindent 10 }}
        # we mount the config file
        {{- if .Values.redis.config }}
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
          readOnly: true
        {{- end }}
      {{- /* monitoring sidecar */}}
      {{- if .Values.redis.monitoring.enabled }}
      - name: redis-exporter
        image: {{ .Values.redis.monitoring.image.name }}:{{ .Values.redis.monitoring.image.tag }}
        imagePullPolicy: {{ .Values.redis.monitoring.image.pullPolicy }}
        ports:
        - containerPort: 9121
          name: metrics
          protocol: TCP
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: session
        resources:
          {{- toYaml .Values.resources.redis_monitor | nindent 10 }}
      {{- end }}
      {{- if .Values.redis.config }}
      volumes:
      - name: redis-config
        configMap:
          name: {{ .Release.Name }}-redis-config
      {{- end }}
---
{{/* The PodMonitor for Redis monitoring */}}
{{- if .Values.redis.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-redis-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  jobLabel: app.kubernetes.io/instance
  podTargetLabels:
  - app.kubernetes.io/component
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
{{- end }}
---
{{/* The Service for Redis */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  type: ClusterIP
{{- end  -}}
